### ISSUE TITLE
Texte CONTRIBUTING.md

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/portailva#1]
Le texte du point 3 de la page [CONTRIBUTING](https://github.com/VAINSALyon/portailva/blob/dev/CONTRIBUTING.md) concernant les issues est étrange.

La fin n'est pas cohérente !

**Comment by martinezleoml** [comment]
Je crois qu'il n'est pas possible d'assigner quelqu'un d'extérieur à l'organisation sur une tâche. D'où l'idée de ce point.

**Comment by Crocmagnon** [comment]
Je parle de la partie "et est sera marquée comme "en cours")" :)

**Comment by martinezleoml** [comment]
Ok je vois. Je propose donc de supprimer simplement cette partie.

**Comment by Crocmagnon** [comment]
C'est fait ! Voir 5ddd544.
