### ISSUE TITLE
Newsletter VA - Ajouter le bloc "événements"

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#12]
La newsletter VA est découpée en trois sections :
- L'association à la une
- Les articles
- Les événements

La dernière section se compose d'un export des événements à venir dans les deux prochaines semaines (attention : impossible de trier sur date de début dans le cas où un événement dure du mercredi au vendredi, il doit apparaître dans la newsletter du jeudi), triés par date de début. Dans la newsletter, les informations sont réduites au minimum : nom de l'événement, date, heure, lieu.

**Comment by PhilippeVienne** [comment]
Events can now be added to newsletters
