### ISSUE TITLE
Amélioration de la génération de la newsletter

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#22]
ajout d'un filtre sur les articles (articles pas déjà envoyés) et sur les événements (événements dont la date de fin n'est pas encore passée + tri des événements par date de début)

**Comment by PhilippeGeek** [comment]
ajout d'un filtre sur les articles (articles pas déjà envoyés) et sur les événements (événements dont la date de fin n'est pas encore passée + tri des événements par date de début)
