### ISSUE TITLE
Ajout d'une gestion d'arborescence de fichiers dans les ressources

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#23]

**Comment by PhilippeVienne** [comment]
C'est vraiment bloquant ? ou juste important ?

**Comment by rbourrier** [comment]
Plus ou moins, disons que les ressources seront vraiment utilisables quand ce sera possible, d'ici là on ne peut pas mettre plus de 5/10 fichiers sans perdre en lisibiltié

**Comment by PhilippeVienne** [comment]
@rbourrier La fonctionnalité sera présente dans la prochaine version (fin de la semaine)
@Crocmagnon Peux-tu revoir ma PR ?
