### ISSUE TITLE
Enregistrement du nombre de membres actifs

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#38]
Actuellement ne fonctionne pas, si on entre un nombre dans le champ et qu'on valide la modification n'est pas prise en compte

**Comment by Crocmagnon** [comment]
Résolu sauf dans le cas de la création d'une asso : le champ existe mais ne se sauvegarde pas. Je regarde.

**Comment by Crocmagnon** [comment]
Résolu.
