### ISSUE TITLE
Ordre alphabétique assos / tri sur état

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#39]
rétablir les petites flèches en haut des listes afin de pouvoir classer les asso par ordre alphabétique dans la rubrique liste des associations
idem pour situation administrative - liste des critères - ETAT/ ACTION  impossibilité de sélectionner ETAT  (rouge ou vert)

**Comment by Crocmagnon** [comment]
(Régression parce que la feature existait avant et a été supprimée)
