### ISSUE TITLE
Réparer les API d'export

### ISSUE THREAD

**Issue by rbourrier** [BdEINSALyon/portailva#50]
Événements et botinsa, pour tester voir intranet.insa-lyon.fr qui les récupère :)

**Comment by PhilippeVienne** [comment]
@rbourrier qui est chargé de ça à l'INSA ?
Est-ce qu'un site Bot'INSA à nous avec juste un lien depuis l'intranet ne serait pas mieux ?

**Comment by rbourrier** [comment]
C'est la DirCom qui s'en occupe, mais ça marchait bien avant donc c'est de
notre côté que c'est cassé.

2017-03-24 15:38 GMT+01:00 Philippe Vienne <notifications@github.com>:

**Comment by PhilippeVienne** [comment]
L'api fonctionne toujours de mon côté et n'a pas changé

**Comment by rbourrier** [comment]
Bah c'est assez embêtant parce que la DirCom n'a rien changé mais ça ne
marche plus de leur côté. Je leur répond quoi ?

2017-03-24 16:54 GMT+01:00 Philippe Vienne <notifications@github.com>:
