### ISSUE TITLE
Impossible d'ajouter un mandat

### ISSUE THREAD

**Issue by MathisHammel** [BdEINSALyon/portailva#72]
Je me prends une belle erreur 500 générique lors de l'enregistrement de mandat. Mon asso est INSA Talks, et nous n'avons pas de mandat enregistré sur la plateforme.
Je ferais volontiers le fix mais j'ai moyennement le temps et je n'ai pas les logs serveur :wink:

**Comment by Crocmagnon** [comment]
Est-ce que tu peux fournir les données que tu saisis lors de l'enregistrement de ton mandat s'il te plaît ? 😊 
En production avec un compte admin je n'ai pas d'erreur lors de la création d'un mandat du 24/10/2017 au 23/10/2018 pour INSA Talks.

**Comment by MathisHammel** [comment]
[facepalm] je viens de me rendre compte que j'essayais de créer un mandat qui s'arrête le 31/06/2018, mais juin n'a que 30 jours....
